# GitHub Sponsors
github: sandr

# Ko-fi (optional alternative)
# ko_fi: username

# Patreon (optional alternative)
# patreon: username

# Open Collective (optional alternative)
# open_collective: username

# Tidelift (optional for commercial support)
# tidelift: "pypi/filesystem-mcp"

# Community Bridge (optional)
# community_bridge: project-name

# Buy Me a Coffee (optional alternative)
# buy_me_a_coffee: username
